### ISSUE TITLE
Does not work with meteor 1.5 and updated ecmascript-runtime-client@0.4.2 

### ISSUE THREAD

**Issue by teknologist** [zodern/minify-js-sourcemaps#2]
If I add ~~bundle-visualizer~~ **(It is due to upgraded ecmascript-runtime-client@0.4.2 . see below)**.

```
Meteor run --production fails with this:

Warning: The --production flag should only be used to simulate production bundling for testing purposes. Use meteor build to create a bundle for
production deployment. See: https://guide.meteor.com/deployment.html

=> Started proxy.
WARN: Output exceeds 32000 characters        \
WARN: Output exceeds 32000 characters
WARN: Output exceeds 32000 characters
WARN: Output exceeds 32000 characters
WARN: Output exceeds 32000 characters
WARN: Output exceeds 32000 characters
WARN: Output exceeds 32000 characters
WARN: Output exceeds 32000 characters
{ [SyntaxError: Unexpected token: operator (>)]
  message: 'Unexpected token: operator (>)',
  filename: 0,
  line: 12,
  col: 22,
  pos: 1172 }
/Users/eric/.meteor/packages/templating-compiler/.1.3.2.12ln3hn++os+web.browser+web.cordova/plugin.compileTemplatesBatch.os/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:190
      throw error;
      ^

Error: Path reservation conflict: app.js
    at Builder.reserve (/tools/isobuild/builder.js:333:15)
    at /tools/isobuild/bundler.js:1553:15
    at /tools/isobuild/bundler.js:1545:11
    at Array.forEach (native)
    at /tools/isobuild/bundler.js:1544:20
    at Array.forEach (native)
    at ClientTarget.<anonymous> (/tools/isobuild/bundler.js:1543:30)
    at ClientTarget.write (/tools/isobuild/bundler.js:1552:5)
    at /tools/isobuild/bundler.js:2563:30
    at /tools/isobuild/bundler.js:2696:9
    at Array.forEach (native)
    at /tools/isobuild/bundler.js:2686:26
    at /tools/isobuild/bundler.js:3027:22
    at /tools/utils/buildmessage.js:271:13
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:264:29
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:262:18
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:253:23
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.capture (/tools/utils/buildmessage.js:252:19)
    at bundle (/tools/isobuild/bundler.js:2860:31)
    at /tools/isobuild/bundler.js:2807:32
    at Object.withCache (/tools/fs/files.js:1652:12)
    at Object.exports.bundle (/tools/isobuild/bundler.js:2807:16)
    at /tools/runners/run-app.js:588:36
    at Function.run (/tools/tool-env/profile.js:490:12)
    at bundleApp (/tools/runners/run-app.js:587:34)
    at [object Object]._.extend._runOnce (/tools/runners/run-app.js:631:35)
    at [object Object]._.extend._fiber (/tools/runners/run-app.js:890:28)
    at /tools/runners/run-app.js:417:12
npm ERR! code ELIFECYCLE
npm ERR! errno 1
```

As soon as I replace your minifier-js by meteor's. it works like a charm.

Any idea ?

**Comment by teknologist** [comment]
Well, 
in fact it seems it has nothing to do with bundle-visualizer.

That happens on our CI:
```

Error: Path reservation conflict: app.js
    at Builder.reserve (/tools/isobuild/builder.js:333:15)
    at /tools/isobuild/bundler.js:1553:15
    at /tools/isobuild/bundler.js:1545:11
    at Array.forEach (native)
    at /tools/isobuild/bundler.js:1544:20
    at Array.forEach (native)
    at ClientTarget.<anonymous> (/tools/isobuild/bundler.js:1543:30)
    at ClientTarget.write (/tools/isobuild/bundler.js:1552:5)
    at /tools/isobuild/bundler.js:2563:30
    at /tools/isobuild/bundler.js:2696:9
    at Array.forEach (native)
    at /tools/isobuild/bundler.js:2686:26
    at /tools/isobuild/bundler.js:3027:22
    at /tools/utils/buildmessage.js:271:13
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:264:29
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:262:18
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:253:23
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.capture (/tools/utils/buildmessage.js:252:19)
    at bundle (/tools/isobuild/bundler.js:2860:31)
    at /tools/isobuild/bundler.js:2807:32
    at Object.withCache (/tools/fs/files.js:1652:12)
    at Object.exports.bundle (/tools/isobuild/bundler.js:2807:16)
    at buildCommand (/tools/cli/commands.js:949:30)
    at Command.func (/tools/cli/commands.js:824:12)
    at /tools/cli/main.js:1483:23
```


It seems it happens after these 2 meteor packages were upgraded earlier today:

```
ecmascript-runtime-client@0.4.1 -> ecmascript-runtime-client@0.4.2 
and
minimongo@1.2.0 -> minimongo@1.2.1 
```

It does not happen of course if I build with meteor build --debug

**Comment by teknologist** [comment]
I can confirm rolling back these packages fixes it.

**Comment by teknologist** [comment]
@zodern Hi, any idea on this ?

**Comment by teknologist** [comment]
If I build with 

`meteor build --debug
`
No issues

**Comment by hexsprite** [comment]
@teknologist i'm running 1.5.1-rc.3 which has ecmascript-runtime-client@0.5.0-beta.2 and I am not getting this error.

**Comment by teknologist** [comment]
@hexsprite Thanks for your info! 
Tried upgrading to METEOR@1.5.1-rc.3  … and it did not solve the issue.
Maybe it has to do with some atmosphere or npm package I have...

**Comment by teknologist** [comment]
Upgrading to METEOR@1.6-beta.4  makes the error disappear and solves the issue...

**Comment by teknologist** [comment]
Replacing the last lines in standard-minifier-js-sourcemaps/plugin/minify-js.js with:

```
if (files.length) {
    files[0].addJavaScript({
      data: concat.content.toString(),
      sourceMap: concat.sourceMap
    });
  }
```

Thus removing the path element fixes the build but I don't know if it'll work as the name of the js file is dynamic and the file reference for the sourcemap won't match

**Comment by hexsprite** [comment]
yeah probably another package is pulling in the regular Meteor minifier and they're both registering for the same file?

**Comment by teknologist** [comment]
@hexsprite well the thing is I don't see standard-minifier.js in .meteor/versions. Only zodern's is there.... 
Last but not least I have tried changing the path string to some random thing just to make sure there is no conflict...still fails the same way...

_Sent from my Huawei Nexus 6P using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by hexsprite** [comment]
2 ideas - you could follow some of the tips here to try to search for the package: https://stackoverflow.com/questions/26153603/how-to-show-all-package-dependency-tree

or you could add some debug code to a Meteor devel build to show what other package has registered the same file

**Comment by teknologist** [comment]
Indeed but did you read my latest comment?
I tried changing the path from app.js to another string in my packages directory (i.e. using a customized version of the package) and the error occurred with my new modified name...

**Comment by teknologist** [comment]
@hexsprite Well just removing the path argument as per my comment seems to work. Chrome sees my sourcemaps on meteor --production build

**Comment by teknologist** [comment]
And sentry seems to pick theme up !

Output from sentry-cli upload-sourcemaps --rewrite and validate:

```
> Analyzing 18 sources
> Rewriting sources
> Adding source map references
> Uploading source maps for release 0.9.49-live

Source Map Upload Report
  Scripts
    ~/app/sw.js
    ~/dynamic/node_modules/intl/index.js
    ~/packages/oauth/end_of_popup_response.js
    ~/packages/oauth/end_of_redirect_response.js
  Minified Scripts
    ~/298e50ed124fd5566b85947a31a09d3a0fe52f63.js (sourcemap at 298e50ed124fd5566b85947a31a09d3a0fe52f63.js.map)
    ~/dynamic/node_modules/intl/lib/core.js (sourcemap at core.js.map)
    ~/dynamic/node_modules/intl/locale-data/complete.js (sourcemap at complete.js.map)
    ~/dynamic/node_modules/intl/locale-data/jsonp/fr.js (sourcemap at fr.js.map)
    ~/dynamic/node_modules/pdfmake/build/pdfmake.min.js (sourcemap at pdfmake.min.js.map)
    ~/dynamic/node_modules/pdfmake/build/vfs_fonts.js (sourcemap at vfs_fonts.js.map)
  Source Maps
    ~/298e50ed124fd5566b85947a31a09d3a0fe52f63.js.map
    ~/dynamic/node_modules/intl/index.js.map
    ~/dynamic/node_modules/intl/lib/core.js.map
    ~/dynamic/node_modules/intl/locale-data/complete.js.map
    ~/dynamic/node_modules/intl/locale-data/jsonp/fr.js.map
    ~/dynamic/node_modules/intl/package.json.map
    ~/dynamic/node_modules/pdfmake/build/pdfmake.min.js.map
    ~/dynamic/node_modules/pdfmake/build/vfs_fonts.js.map
```

Will see next time there is an exception...

**Comment by teknologist** [comment]
Well sentry doesn't seem to pickup the sourcemaps

**Comment by teknologist** [comment]
Well I solved the issue in kind of a hacky way.
I let the minifier generate the files with the random name.
Then I process the minified js file with sed to replace the production.min.js.map string in sourceMappingURL with the actual random text file.

It's a bit hacky but it does work:


```
arr=( $(find $1 -name *.js -type f) )
fullfile=${arr[0]}
filename=$(basename "$fullfile")
sed -i '' "s/sourceMappingURL=production.min.js.map/sourceMappingURL=~\/${filename}.map/g" $fullfile
echo "Corrected sourceMappingURL in $fullfile with $filename filename"
```


By the way I spent a couple of hours trying to find the package issue with no luck. Even created a test todos-react meteor app and added all my meteor packages as well as npm packages and couldn't reproduce the issue...Hence the reason I stopped wasting time and went for the hacky fix.

**Comment by zodern** [comment]
I am releasing an update today that fixes using dynamic imports, which was the cause of `Path reservation conflict: app.js`.

```
{ [SyntaxError: Unexpected token: operator (>)]
  message: 'Unexpected token: operator (>)',
  filename: 0,
  line: 12,
  col: 22,
  pos: 1172 }
```
This error is from uglify. It falls back to `babel-minify` for that file, but doesn't create any sourcemaps for it. I created #5 for that.

**Comment by zodern** [comment]
The update is now available.

**Comment by jlukic** [comment]
I'm still getting the same error with the updated `2.2` package

```javascript
at /tools/runners/run-app.js:408:12
 message: 'Unexpected token: operator (>)',
 filename: 0,
 line: 511,
 col: 43,
 pos: 58481 }

```

**Comment by zodern** [comment]
Could you please show the full logs?

**Comment by jlukic** [comment]
This is with
```
zodern:minifier-js@2.3.0
zodern:standard-minifier-js@2.4.0
```

```javascript
 { SyntaxError: Unexpected token: operator (>)
     at JS_Parse_Error.get (eval at <anonymous> (/root/.meteor/packages/zodern_standard-minifier-js/.2.4.0.1wljqkg.wb1++os+web.browser+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/zodern_minifier-js/node_modules/uglify-js/tools/node.js:27:1), <anonymous>:86:23)
     at formatError (util.js:642:16)
     at formatValue (util.js:544:18)
     at inspect (util.js:324:10)
     at format (util.js:191:12)
     at Console.log (console.js:130:21)
     at meteorJsMinify (packages/zodern_minifier-js.js:44:13)
     at packages/minifyStdJS/plugin/minify-js.js:147:20
     at Array.forEach (<anonymous>)
     at MeteorBabelMinifier.processFilesForBundle (packages/minifyStdJS/plugin/minify-js.js:135:9)
     at __bottom_mark__ (/tools/utils/parse-stack.js:64:14)
     at /tools/isobuild/bundler.js:1248:9
     at /tools/utils/buildmessage.js:359:18
     at exports.EnvironmentVariable.withValue (/tools/utils/fiber-helpers.js:89:14)
     at /tools/utils/buildmessage.js:352:34
     at exports.EnvironmentVariable.withValue (/tools/utils/fiber-helpers.js:89:14)
     at /tools/utils/buildmessage.js:350:23
     at exports.EnvironmentVariable.withValue (/tools/utils/fiber-helpers.js:89:14)
     at Object.enterJob (/tools/utils/buildmessage.js:324:26)
     at ClientTarget.minifyJs (/tools/isobuild/bundler.js:1245:18)
     at buildmessage.enterJob (/tools/isobuild/bundler.js:856:16)
     at /tools/utils/buildmessage.js:359:18
     at exports.EnvironmentVariable.withValue (/tools/utils/fiber-helpers.js:89:14)
     at /tools/utils/buildmessage.js:352:34
     at exports.EnvironmentVariable.withValue (/tools/utils/fiber-helpers.js:89:14)
     at /tools/utils/buildmessage.js:350:23
     at exports.EnvironmentVariable.withValue (/tools/utils/fiber-helpers.js:89:14)
     at Object.enterJob (/tools/utils/buildmessage.js:324:26)
     at ClientTarget.make (/tools/isobuild/bundler.js:818:18)
     at /tools/isobuild/bundler.js:2926:14
     at /tools/isobuild/bundler.js:3015:20
     at Array.forEach (<anonymous>)
     at Function._.each._.forEach (/root/.meteor/packages/meteor-tool/.1.6.0_1.11dnljz++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
     at /tools/isobuild/bundler.js:3014:7
     at /tools/utils/buildmessage.js:271:13
     at exports.EnvironmentVariable.withValue (/tools/utils/fiber-helpers.js:89:14)
     at /tools/utils/buildmessage.js:264:29
     at exports.EnvironmentVariable.withValue (/tools/utils/fiber-helpers.js:89:14)
     at /tools/utils/buildmessage.js:262:18
     at exports.EnvironmentVariable.withValue (/tools/utils/fiber-helpers.js:89:14)
     at /tools/utils/buildmessage.js:253:23
     at exports.EnvironmentVariable.withValue (/tools/utils/fiber-helpers.js:89:14)
     at Object.capture (/tools/utils/buildmessage.js:252:19)
     at bundle (/tools/isobuild/bundler.js:2907:31)
     at files.withCache (/tools/isobuild/bundler.js:2854:32)
     at Object.withCache (/tools/fs/files.js:1658:12)
     at Object.exports.bundle (/tools/isobuild/bundler.js:2854:16)
     at Profile.run (/tools/runners/run-app.js:579:36)
     at Function.run (/tools/tool-env/profile.js:490:12)
     at bundleApp (/tools/runners/run-app.js:578:34)
     at AppRunner._runOnce (/tools/runners/run-app.js:622:35)
     at AppRunner._fiber (/tools/runners/run-app.js:880:28)
     at /tools/runners/run-app.js:408:12
   message: 'Unexpected token: operator (>)',
   filename: 0,
   line: 511,
   col: 43,
   pos: 58481 }
 WARN: Output exceeds 32000 characters
```

**Comment by zodern** [comment]
Uglify failed minifying the file. It would then fall back to using babel.minify.

Everything should be be minified correctly. The only problem is that that one source file wouldn't have any mappings in the sourcemap. #5 would fix it.

**Comment by jlukic** [comment]
Isn't #5 in `2.2.0` though, this is why I'm confused (above error is with `2.3.0`)
