### ISSUE TITLE
Meteor 1.8 support

### ISSUE THREAD

**Issue by namirsab** [zodern/minify-js-sourcemaps#22]
Hi evetyone,
First of all, thanks for this.

Just wanted to know if anybody is using this together with meteor 1.8 and if it works for you, and if so, what should I do?
I get some errors like:

```
SyntaxError: Unexpected token: name (InheritPrototype)
    at JS_Parse_Error.get (eval at <anonymous> (/home/namir-sab/.meteor/packages/zodern_standard-minifier-js/.2.0.0.hnbl9.uddy8h++os+web.browser+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/zodern_minifier-js/node_modules/uglify-js/tools/node.js:27:1), <anonymous>:86:23)
    at formatError (util.js:610:16)
    at formatValue (util.js:514:18)
    at inspect (util.js:294:10)
    at format (util.js:161:12)
    at Console.log (console.js:130:21)
    at meteorJsMinify (packages/zodern_minifier-js.js:44:13)
    at packages/minifyStdJS_plugin.js:150:24
    at Array.forEach (<anonymous>)
    at MeteorBabelMinifier.processFilesForBundle (packages/minifyStdJS_plugin.js:140:9)
    at __bottom_mark__ (/tools/utils/parse-stack.js:69:14)
    at /tools/isobuild/bundler.js:1331:11
    at /tools/utils/buildmessage.js:359:18
    at exports.EnvironmentVariable.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:352:34
    at exports.EnvironmentVariable.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:350:23
    at exports.EnvironmentVariable.withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.enterJob (/tools/utils/buildmessage.js:324:26)
    at ClientTarget.minifyJs (/tools/isobuild/bundler.js:1328:18)
    at buildmessage.enterJob (/tools/isobuild/bundler.js:870:16)
    at /tools/utils/buildmessage.js:359:18
    at exports.EnvironmentVariable.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:352:34
    at exports.EnvironmentVariable.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:350:23
    at exports.EnvironmentVariable.withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.enterJob (/tools/utils/buildmessage.js:324:26)
    at ClientTarget.make (/tools/isobuild/bundler.js:829:18)
    at /tools/isobuild/bundler.js:3115:14
    at webArchs.forEach.arch (/tools/isobuild/bundler.js:3266:25)
    at Array.forEach (<anonymous>)
    at /tools/isobuild/bundler.js:3220:14
    at /tools/utils/buildmessage.js:271:13
    at exports.EnvironmentVariable.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:264:29
    at exports.EnvironmentVariable.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:262:18
    at exports.EnvironmentVariable.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:253:23
    at exports.EnvironmentVariable.withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.capture (/tools/utils/buildmessage.js:252:19)
    at bundle (/tools/isobuild/bundler.js:3096:31)
    at files.withCache (/tools/isobuild/bundler.js:3041:32)
    at Object.withCache (/tools/fs/files.js:1712:12)
    at Object.bundle (/tools/isobuild/bundler.js:3041:16)
    at Profile.run (/tools/runners/run-app.js:569:24)
    at Function.run (/tools/tool-env/profile.js:490:12)
    at bundleApp (/tools/runners/run-app.js:568:34)
    at AppRunner._runOnce (/tools/runners/run-app.js:610:35)
    at AppRunner._fiber (/tools/runners/run-app.js:908:28)
    at /tools/runners/run-app.js:398:12
  message: 'Unexpected token: name (InheritPrototype)',
  filename: 0,
  line: 43,
  col: 4,
  pos: 2291 }
```

when running meteor with --production flag.

**Comment by teknologist** [comment]
@namirsab no issue whatsoever here with meteor 1.8.1

**Comment by namirsab** [comment]
@teknologist thanks for your answer.

So here what I did:
* Uninstalled the standard minifiers
* Install the new one
* Build the app.

When I build, it just crashes running out of memory.
When I try to run with the `--production`, then we get all those errors and then it crashes as well with memory 

Anything I'm missing?

**Comment by zodern** [comment]
Version 4 has been updated to match the latest version of standard-minifier-js which should fix this.
